package View.ChonMon;

import Manager.JDBCConnection;
import Manager.ManagerHoaDon;
import Service.ChiTietHoaDonService;
import Service.HoaDonService;
import Service.TraCuuBanService;
import View.DatBan.TraCuuBan;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.CheckBox;
import javax.swing.JOptionPane;
import model.HoaDon;
import model.MonAn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class ChonMonFrame extends javax.swing.JFrame {

    HoaDonService hoaDonService = new HoaDonService();
    TraCuuBanService traCuuBanService = new TraCuuBanService();
    ChiTietHoaDonService chonMonService = new ChiTietHoaDonService();
    ManagerHoaDon managerHoaDon = new ManagerHoaDon();
            // TODO add your handling code here:
    
    /**
     * Creates new form ChonMonFrame
     */
    public ChonMonFrame(String id) throws SQLException {
        initComponents();
        idBA.setText(traCuuBanService.getIdTabel(id));
        MonAn monAn = new MonAn();
    }

    public ChonMonFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public String getIDBA() {
        return idBA.getText();
    }

    public int getIdHD() throws SQLException {
        HoaDon hoaDon = new HoaDon();
        Connection connection = JDBCConnection.JDBCConnection();
        String sql = "select max(idHoaDon) as idHD\n"
                + "from HoaDon";
        try {
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                hoaDon.setIdHoaDon(rs.getInt("idHD"));
                return hoaDon.getIdHoaDon();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return hoaDon.getIdHoaDon();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
<<<<<<< HEAD
        submitButton = new javax.swing.JButton();
=======
        submitButton_335 = new javax.swing.JButton();
>>>>>>> MainFrame-ChonMon
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gia1 = new javax.swing.JLabel();
        gia2 = new javax.swing.JLabel();
        gia3 = new javax.swing.JLabel();
        gia4 = new javax.swing.JLabel();
        gia5 = new javax.swing.JLabel();
        gia6 = new javax.swing.JLabel();
        gia7 = new javax.swing.JLabel();
        gia8 = new javax.swing.JLabel();
        gia9 = new javax.swing.JLabel();
        gia10 = new javax.swing.JLabel();
<<<<<<< HEAD
        jButton2 = new javax.swing.JButton();
=======
        backButton_335 = new javax.swing.JButton();
>>>>>>> MainFrame-ChonMon
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        idBA = new javax.swing.JLabel();
        MonAnpn = new javax.swing.JPanel();
<<<<<<< HEAD
        MA001 = new javax.swing.JCheckBox();
        MA003 = new javax.swing.JCheckBox();
        MA002 = new javax.swing.JCheckBox();
        MA004 = new javax.swing.JCheckBox();
        MA005 = new javax.swing.JCheckBox();
        MA006 = new javax.swing.JCheckBox();
        MA007 = new javax.swing.JCheckBox();
        MA008 = new javax.swing.JCheckBox();
        MA009 = new javax.swing.JCheckBox();
        MA010 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        soLuong2 = new com.raven.suportSwing.Combobox();
        soLuong1 = new com.raven.suportSwing.Combobox();
        soLuong3 = new com.raven.suportSwing.Combobox();
        soLuong4 = new com.raven.suportSwing.Combobox();
        soLuong5 = new com.raven.suportSwing.Combobox();
        soLuong6 = new com.raven.suportSwing.Combobox();
        soLuong7 = new com.raven.suportSwing.Combobox();
        soLuong8 = new com.raven.suportSwing.Combobox();
        soLuong9 = new com.raven.suportSwing.Combobox();
        soLuong10 = new com.raven.suportSwing.Combobox();
=======
        MA001_335 = new javax.swing.JCheckBox();
        MA003_335 = new javax.swing.JCheckBox();
        MA002_335 = new javax.swing.JCheckBox();
        MA004_335 = new javax.swing.JCheckBox();
        MA005_335 = new javax.swing.JCheckBox();
        MA006_335 = new javax.swing.JCheckBox();
        MA007_335 = new javax.swing.JCheckBox();
        MA008_335 = new javax.swing.JCheckBox();
        MA009_335 = new javax.swing.JCheckBox();
        MA010_335 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        soLuong2_335 = new com.raven.suportSwing.Combobox();
        soLuong1_335 = new com.raven.suportSwing.Combobox();
        soLuong3_335 = new com.raven.suportSwing.Combobox();
        soLuong4_335 = new com.raven.suportSwing.Combobox();
        soLuong5_335 = new com.raven.suportSwing.Combobox();
        soLuong6_335 = new com.raven.suportSwing.Combobox();
        soLuong7_335 = new com.raven.suportSwing.Combobox();
        soLuong8_335 = new com.raven.suportSwing.Combobox();
        soLuong9_335 = new com.raven.suportSwing.Combobox();
        soLuong10_335 = new com.raven.suportSwing.Combobox();
>>>>>>> MainFrame-ChonMon
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Tên Món");

<<<<<<< HEAD
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/check-mark.png"))); // NOI18N
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
=======
        submitButton_335.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        submitButton_335.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/check-mark.png"))); // NOI18N
        submitButton_335.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton_335ActionPerformed(evt);
>>>>>>> MainFrame-ChonMon
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("ID bàn:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Số lượng");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Giá");

        gia1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gia1.setText("200000");

        gia2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gia2.setText("400000");

        gia3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gia3.setText("330000");

        gia4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gia4.setText("700000");

        gia5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gia5.setText("520000");

        gia6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gia6.setText("100000");

        gia7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gia7.setText("450000");

        gia8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gia8.setText("300000");

        gia9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gia9.setText("20000");

        gia10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gia10.setText("450000");
<<<<<<< HEAD

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/beefsteak.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chicken-leg.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fried-chicken.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/crocodile.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sheep.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sushi.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hot-pot.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/curry-rice.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/water.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wine-bottle.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("ID Món");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setText("Beef steak");
        jLabel13.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel14.setText("Gà quay");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel15.setText("Gà rán nóng Nashville");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel16.setText("Cá sấu Châu Phi nướng");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel17.setText("Cừu New Zeland hấp");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel18.setText("Sushi Nhật Bản ");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel19.setText("Lẩu đặc biệt");

=======

        backButton_335.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        backButton_335.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        backButton_335.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton_335ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/beefsteak.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chicken-leg.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fried-chicken.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/crocodile.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sheep.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sushi.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hot-pot.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/curry-rice.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/water.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wine-bottle.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("ID Món");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setText("Beef steak");
        jLabel13.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel14.setText("Gà quay");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel15.setText("Gà rán nóng Nashville");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel16.setText("Cá sấu Châu Phi nướng");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel17.setText("Cừu New Zeland hấp");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel18.setText("Sushi Nhật Bản ");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel19.setText("Lẩu đặc biệt");

>>>>>>> MainFrame-ChonMon
        jLabel20.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel20.setText("Cơm rang bò");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel21.setText("Rượu vang");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel26.setText("Nước suối");

        idBA.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        idBA.setForeground(new java.awt.Color(51, 153, 255));
<<<<<<< HEAD
        idBA.setText("ID Bàn ăn");

        MonAnpn.setBackground(new java.awt.Color(255, 255, 255));

        MA001.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA001.setText("MA001");

        MA003.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA003.setText("MA003");

        MA002.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA002.setText("MA002");

        MA004.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA004.setText("MA004");

        MA005.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA005.setText("MA005");

        MA006.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA006.setText("MA006");

        MA007.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA007.setText("MA007");

        MA008.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA008.setText("MA008");

        MA009.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA009.setText("MA009");

        MA010.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA010.setText("MA010");
=======
        idBA.setText("idBA");

        MonAnpn.setBackground(new java.awt.Color(255, 255, 255));

        MA001_335.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA001_335.setText("MA001");

        MA003_335.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA003_335.setText("MA003");

        MA002_335.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA002_335.setText("MA002");

        MA004_335.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA004_335.setText("MA004");

        MA005_335.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA005_335.setText("MA005");

        MA006_335.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA006_335.setText("MA006");

        MA007_335.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA007_335.setText("MA007");

        MA008_335.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA008_335.setText("MA008");

        MA009_335.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA009_335.setText("MA009");

        MA010_335.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MA010_335.setText("MA010");
>>>>>>> MainFrame-ChonMon

        javax.swing.GroupLayout MonAnpnLayout = new javax.swing.GroupLayout(MonAnpn);
        MonAnpn.setLayout(MonAnpnLayout);
        MonAnpnLayout.setHorizontalGroup(
            MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonAnpnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addComponent(MA003)
                    .addComponent(MA001)
                    .addComponent(MA002))
=======
                    .addComponent(MA003_335)
                    .addComponent(MA001_335)
                    .addComponent(MA002_335))
>>>>>>> MainFrame-ChonMon
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MonAnpnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                        .addComponent(MA004)
                        .addComponent(MA005)
                        .addComponent(MA006)
                        .addComponent(MA007)
                        .addComponent(MA008)
                        .addComponent(MA009)
                        .addComponent(MA010))
=======
                        .addComponent(MA004_335)
                        .addComponent(MA005_335)
                        .addComponent(MA006_335)
                        .addComponent(MA007_335)
                        .addComponent(MA008_335)
                        .addComponent(MA009_335)
                        .addComponent(MA010_335))
>>>>>>> MainFrame-ChonMon
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        MonAnpnLayout.setVerticalGroup(
            MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonAnpnLayout.createSequentialGroup()
<<<<<<< HEAD
                .addComponent(MA001)
                .addGap(40, 40, 40)
                .addComponent(MA002)
                .addGap(50, 50, 50)
                .addComponent(MA003)
                .addContainerGap(539, Short.MAX_VALUE))
=======
                .addContainerGap()
                .addComponent(MA001_335)
                .addGap(42, 42, 42)
                .addComponent(MA002_335)
                .addGap(61, 61, 61)
                .addComponent(MA003_335)
                .addContainerGap(517, Short.MAX_VALUE))
>>>>>>> MainFrame-ChonMon
            .addGroup(MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MonAnpnLayout.createSequentialGroup()
                    .addGap(213, 213, 213)
                    .addGroup(MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MonAnpnLayout.createSequentialGroup()
                            .addGroup(MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(MonAnpnLayout.createSequentialGroup()
                                    .addGroup(MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(MonAnpnLayout.createSequentialGroup()
                                            .addGroup(MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(MonAnpnLayout.createSequentialGroup()
                                                    .addGroup(MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(MonAnpnLayout.createSequentialGroup()
                                                            .addGroup(MonAnpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(MonAnpnLayout.createSequentialGroup()
<<<<<<< HEAD
                                                                    .addComponent(MA004)
                                                                    .addGap(68, 68, 68))
                                                                .addComponent(MA005))
                                                            .addGap(68, 68, 68))
                                                        .addComponent(MA006))
                                                    .addGap(68, 68, 68))
                                                .addComponent(MA007))
                                            .addGap(68, 68, 68))
                                        .addComponent(MA008))
                                    .addGap(68, 68, 68))
                                .addComponent(MA009))
                            .addGap(68, 68, 68))
                        .addComponent(MA010, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        soLuong2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong2.setToolTipText("");
        soLuong2.setLabeText("");

        soLuong1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong1.setToolTipText("");
        soLuong1.setLabeText("");

        soLuong3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong3.setToolTipText("");
        soLuong3.setLabeText("");

        soLuong4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong4.setToolTipText("");
        soLuong4.setLabeText("");

        soLuong5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong5.setToolTipText("");
        soLuong5.setLabeText("");

        soLuong6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong6.setToolTipText("");
        soLuong6.setLabeText("");

        soLuong7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong7.setToolTipText("");
        soLuong7.setLabeText("");

        soLuong8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong8.setToolTipText("");
        soLuong8.setLabeText("");

        soLuong9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong9.setToolTipText("");
        soLuong9.setLabeText("");

        soLuong10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong10.setToolTipText("");
        soLuong10.setLabeText("");
=======
                                                                    .addComponent(MA004_335)
                                                                    .addGap(68, 68, 68))
                                                                .addComponent(MA005_335))
                                                            .addGap(68, 68, 68))
                                                        .addComponent(MA006_335))
                                                    .addGap(68, 68, 68))
                                                .addComponent(MA007_335))
                                            .addGap(68, 68, 68))
                                        .addComponent(MA008_335))
                                    .addGap(68, 68, 68))
                                .addComponent(MA009_335))
                            .addGap(68, 68, 68))
                        .addComponent(MA010_335, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        soLuong2_335.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong2_335.setToolTipText("");
        soLuong2_335.setLabeText("");

        soLuong1_335.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong1_335.setToolTipText("");
        soLuong1_335.setLabeText("");

        soLuong3_335.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong3_335.setToolTipText("");
        soLuong3_335.setLabeText("");

        soLuong4_335.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong4_335.setToolTipText("");
        soLuong4_335.setLabeText("");

        soLuong5_335.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong5_335.setToolTipText("");
        soLuong5_335.setLabeText("");

        soLuong6_335.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong6_335.setToolTipText("");
        soLuong6_335.setLabeText("");

        soLuong7_335.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong7_335.setToolTipText("");
        soLuong7_335.setLabeText("");

        soLuong8_335.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong8_335.setToolTipText("");
        soLuong8_335.setLabeText("");

        soLuong9_335.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong9_335.setToolTipText("");
        soLuong9_335.setLabeText("");

        soLuong10_335.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        soLuong10_335.setToolTipText("");
        soLuong10_335.setLabeText("");
>>>>>>> MainFrame-ChonMon

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
<<<<<<< HEAD
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
=======
                        .addComponent(backButton_335, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
>>>>>>> MainFrame-ChonMon
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
<<<<<<< HEAD
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
=======
                        .addComponent(submitButton_335, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
>>>>>>> MainFrame-ChonMon
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MonAnpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(gia1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gia2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gia3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gia4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gia5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gia6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gia7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gia8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gia9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gia10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
<<<<<<< HEAD
                                .addComponent(soLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
=======
                                .addComponent(soLuong1_335, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soLuong2_335, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong3_335, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong4_335, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong5_335, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong6_335, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong7_335, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong8_335, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong9_335, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soLuong10_335, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
>>>>>>> MainFrame-ChonMon
                    .addComponent(jSeparator1))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(idBA, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idBA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(MonAnpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
=======
>>>>>>> MainFrame-ChonMon
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6)
<<<<<<< HEAD
                                    .addComponent(soLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
=======
                                    .addComponent(soLuong1_335, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
>>>>>>> MainFrame-ChonMon
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(gia2)
                                                .addGap(20, 20, 20)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(gia3)
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
<<<<<<< HEAD
                                                    .addComponent(soLuong4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
=======
                                                    .addComponent(soLuong4_335, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
>>>>>>> MainFrame-ChonMon
                                                    .addComponent(gia4))
                                                .addGap(3, 3, 3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel15))
                                                .addGap(55, 55, 55)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(231, 231, 231)
<<<<<<< HEAD
                                                .addComponent(soLuong8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(soLuong9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(gia7))
                                                .addGap(22, 22, 22))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addGap(13, 13, 13))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(soLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(soLuong3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
=======
                                                .addComponent(soLuong8_335, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(soLuong9_335, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(gia7)))
                                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(soLuong2_335, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(soLuong3_335, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
>>>>>>> MainFrame-ChonMon
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(236, 236, 236)
                                                                .addComponent(jLabel16)
                                                                .addGap(28, 28, 28))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel9)
                                                                .addGap(18, 18, 18)))
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel10)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addComponent(jLabel17)))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel11)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(jLabel18)))
                                                        .addGap(17, 17, 17))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(97, 97, 97)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
<<<<<<< HEAD
                                                                    .addComponent(soLuong5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
=======
                                                                    .addComponent(soLuong5_335, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
>>>>>>> MainFrame-ChonMon
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel14)
                                                                        .addGap(177, 177, 177)
                                                                        .addComponent(gia9)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
<<<<<<< HEAD
                                                                .addComponent(soLuong6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
=======
                                                                .addComponent(soLuong6_335, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
>>>>>>> MainFrame-ChonMon
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(gia1)
                                                                .addGap(311, 311, 311)
                                                                .addComponent(gia10)))
                                                        .addGap(38, 38, 38)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel22)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(23, 23, 23)
                                                        .addComponent(jLabel19)))
                                                .addGap(3, 3, 3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(gia5)
<<<<<<< HEAD
                                                    .addComponent(soLuong7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
=======
                                                    .addComponent(soLuong7_335, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
>>>>>>> MainFrame-ChonMon
                                                .addGap(15, 15, 15)))
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel20)))
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(gia6)
                                        .addGap(36, 36, 36)))
                                .addComponent(jLabel24)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< HEAD
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gia8)
                                    .addComponent(soLuong10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel21)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
=======
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gia8)
                                    .addComponent(soLuong10_335, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel21)))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(MonAnpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton_335, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton_335, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
>>>>>>> MainFrame-ChonMon
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/doAn (1).png"))); // NOI18N
        jLabel1.setText("Chọn món ăn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
=======
    private void submitButton_335ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton_335ActionPerformed
>>>>>>> MainFrame-ChonMon
        int idHD = 3;
        try {
            // lay ra idBA
            idHD = managerHoaDon.getIDHoaDon(getIDBA());
<<<<<<< HEAD
            System.out.println(idHD);
        } catch (SQLException ex) {
            Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (MA001.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA001.getText(), Integer.valueOf(soLuong1.getSelectedItem().toString()));
=======
        } catch (SQLException ex) {
            Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (MA001_335.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA001_335.getText(), Integer.valueOf(String.valueOf(soLuong1_335.getSelectedItem())));
>>>>>>> MainFrame-ChonMon
            } catch (SQLException ex) {
                Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
<<<<<<< HEAD
        if (MA002.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA002.getText(), Integer.valueOf(soLuong1.getSelectedItem().toString()));
=======
        if (MA002_335.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA002_335.getText(), Integer.valueOf(String.valueOf(soLuong2_335.getSelectedItem())));
>>>>>>> MainFrame-ChonMon
            } catch (SQLException ex) {
                Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
<<<<<<< HEAD
        if (MA003.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA003.getText(), Integer.valueOf(soLuong1.getSelectedItem().toString()));
=======
        if (MA003_335.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA003_335.getText(), Integer.valueOf(String.valueOf(soLuong3_335.getSelectedItem())));
>>>>>>> MainFrame-ChonMon
            } catch (SQLException ex) {
                Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
<<<<<<< HEAD
        if (MA004.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA004.getText(), Integer.valueOf(soLuong1.getSelectedItem().toString()));
=======
        if (MA004_335.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA004_335.getText(), Integer.valueOf(String.valueOf(soLuong4_335.getSelectedItem())));
>>>>>>> MainFrame-ChonMon
            } catch (SQLException ex) {
                Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
<<<<<<< HEAD
        if (MA005.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA005.getText(), Integer.valueOf(soLuong1.getSelectedItem().toString()));
=======
        if (MA005_335.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA005_335.getText(), Integer.valueOf(String.valueOf(soLuong5_335.getSelectedItem())));
>>>>>>> MainFrame-ChonMon
            } catch (SQLException ex) {
                Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
<<<<<<< HEAD
        if (MA006.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA006.getText(), Integer.valueOf(soLuong1.getSelectedItem().toString()));
=======
        if (MA006_335.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA006_335.getText(), Integer.valueOf(String.valueOf(soLuong6_335.getSelectedItem())));
>>>>>>> MainFrame-ChonMon
            } catch (SQLException ex) {
                Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
<<<<<<< HEAD
        if (MA007.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA007.getText(), Integer.valueOf(soLuong1.getSelectedItem().toString()));
=======
        if (MA007_335.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA007_335.getText(), Integer.valueOf(String.valueOf(soLuong7_335.getSelectedItem())));
>>>>>>> MainFrame-ChonMon
            } catch (SQLException ex) {
                Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
<<<<<<< HEAD
        if (MA008.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA008.getText(), Integer.valueOf(soLuong1.getSelectedItem().toString()));
=======
        if (MA008_335.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA008_335.getText(), Integer.valueOf(String.valueOf(soLuong8_335.getSelectedItem())));
>>>>>>> MainFrame-ChonMon
            } catch (SQLException ex) {
                Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
<<<<<<< HEAD
        if (MA009.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA009.getText(), Integer.valueOf(soLuong1.getSelectedItem().toString()));
=======
        if (MA009_335.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA009_335.getText(), Integer.valueOf(String.valueOf(soLuong9_335.getSelectedItem())));
>>>>>>> MainFrame-ChonMon
            } catch (SQLException ex) {
                Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
<<<<<<< HEAD
        if (MA010.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA010.getText(), Integer.valueOf(soLuong1.getSelectedItem().toString()));
=======
        if (MA010_335.isSelected()) {
            try {
                chonMonService.addMonAnToChiTietHoaDon(idHD, MA010_335.getText(), Integer.valueOf(String.valueOf(soLuong10_335.getSelectedItem())));
>>>>>>> MainFrame-ChonMon
            } catch (SQLException ex) {
                Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            new TraCuuBan().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
<<<<<<< HEAD
    }//GEN-LAST:event_submitButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
=======
    }//GEN-LAST:event_submitButton_335ActionPerformed

    private void backButton_335ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton_335ActionPerformed
>>>>>>> MainFrame-ChonMon
        try {
            // TODO add your handling code here:
            new TraCuuBan().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ChonMonFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
<<<<<<< HEAD
    }//GEN-LAST:event_jButton2ActionPerformed
=======
    }//GEN-LAST:event_backButton_335ActionPerformed
>>>>>>> MainFrame-ChonMon

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChonMonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChonMonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChonMonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChonMonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
<<<<<<< HEAD
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
=======

>>>>>>> MainFrame-ChonMon

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChonMonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JCheckBox MA001;
    private javax.swing.JCheckBox MA002;
    private javax.swing.JCheckBox MA003;
    private javax.swing.JCheckBox MA004;
    private javax.swing.JCheckBox MA005;
    private javax.swing.JCheckBox MA006;
    private javax.swing.JCheckBox MA007;
    private javax.swing.JCheckBox MA008;
    private javax.swing.JCheckBox MA009;
    private javax.swing.JCheckBox MA010;
    private javax.swing.JPanel MonAnpn;
=======
    private javax.swing.JCheckBox MA001_335;
    private javax.swing.JCheckBox MA002_335;
    private javax.swing.JCheckBox MA003_335;
    private javax.swing.JCheckBox MA004_335;
    private javax.swing.JCheckBox MA005_335;
    private javax.swing.JCheckBox MA006_335;
    private javax.swing.JCheckBox MA007_335;
    private javax.swing.JCheckBox MA008_335;
    private javax.swing.JCheckBox MA009_335;
    private javax.swing.JCheckBox MA010_335;
    private javax.swing.JPanel MonAnpn;
    private javax.swing.JButton backButton_335;
>>>>>>> MainFrame-ChonMon
    private javax.swing.JLabel gia1;
    private javax.swing.JLabel gia10;
    private javax.swing.JLabel gia2;
    private javax.swing.JLabel gia3;
    private javax.swing.JLabel gia4;
    private javax.swing.JLabel gia5;
    private javax.swing.JLabel gia6;
    private javax.swing.JLabel gia7;
    private javax.swing.JLabel gia8;
    private javax.swing.JLabel gia9;
    private javax.swing.JLabel idBA;
<<<<<<< HEAD
    private javax.swing.JButton jButton2;
=======
>>>>>>> MainFrame-ChonMon
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
<<<<<<< HEAD
    private com.raven.suportSwing.Combobox soLuong1;
    private com.raven.suportSwing.Combobox soLuong10;
    private com.raven.suportSwing.Combobox soLuong2;
    private com.raven.suportSwing.Combobox soLuong3;
    private com.raven.suportSwing.Combobox soLuong4;
    private com.raven.suportSwing.Combobox soLuong5;
    private com.raven.suportSwing.Combobox soLuong6;
    private com.raven.suportSwing.Combobox soLuong7;
    private com.raven.suportSwing.Combobox soLuong8;
    private com.raven.suportSwing.Combobox soLuong9;
    private javax.swing.JButton submitButton;
=======
    private com.raven.suportSwing.Combobox soLuong10_335;
    private com.raven.suportSwing.Combobox soLuong1_335;
    private com.raven.suportSwing.Combobox soLuong2_335;
    private com.raven.suportSwing.Combobox soLuong3_335;
    private com.raven.suportSwing.Combobox soLuong4_335;
    private com.raven.suportSwing.Combobox soLuong5_335;
    private com.raven.suportSwing.Combobox soLuong6_335;
    private com.raven.suportSwing.Combobox soLuong7_335;
    private com.raven.suportSwing.Combobox soLuong8_335;
    private com.raven.suportSwing.Combobox soLuong9_335;
    private javax.swing.JButton submitButton_335;
>>>>>>> MainFrame-ChonMon
    // End of variables declaration//GEN-END:variables
}
